### PR TITLE
Feat/user and groups

### PR DESCRIPTION
**Pull request by tonsV2**
The goal of this PR is to implement an administrative interface for handling of users and groups. Eventually it should be possible to add users to groups but I'll leave that for another PR for the sake of making this PR more comprehendable.

There are some unresolved issues that I'd appreciate some support on
* The add group form currently allow submitting without ensuring the name and hostname is properly assigned
* The code for getting the current user is in the wrong place but I'm not sure where to place it
* The code for asserting whether or not a user is an administrator is not only in the wrong place but also far from ideal. Let's have a talk about it :-)

### CODE REVIEW

**Review by HendrikThePendric — CHANGES_REQUESTED** [review]
Some points we should discuss:
- What you currently have implemented as a class should probably be implemented as a Context Provider
- We should probably combine current-user-details, current-user-authority, and current-user-authentication-state in a single place (this can also help us if we ever want to add functionality to re-authenticate via a modal and retry failed attempts
- We should probably make some clear decisions about what should be in a modal and what should have it's own route. We only have very few fields here, so I can imagine that having a route for this would feel like overkill. But it's actually less work to make, and does leave a lot of room for gradually adding more and more fields. I suppose there is even a third option we could consider for stuff like this, which is "inline editing/adding" so editing adding directly in the list. In the end I guess it also depends on what we value most from a UX perspective. 
    - If we make consistency our main driving factor, then we should probably create/edit _everything_ on its own route. We already do that for the `NewInstance` component and IMO there are too many fields to complete there to render the form in a modal. As such you could say this component is the "bottle-neck": we want consistency and have one create-form that is too big for a modal, thus all create-forms need to be in a separate view.
    - If take another approach, and simply focus on each section in isolation and try to optimise the UX for each, then using modals for these small create-forms should probably have our preference because they introduce lees mental overhead for the user.
- Both of the above are valid perspectives IMO, but it probably makes sense to decide which one we want to take so we don't end up having to move lots of stuff around later on. And actually, we should ideally include Joe in this discussion, but I think he's on holiday right now.

**Review by HendrikThePendric — APPROVED** [review]
I rebased the branch onto master and added some changes (aa2d277, 726745a). I personally think it would be ready for merge now.

One possible cause for concern is the failing build step. I'd like to @radnov to look at that and either fix it or tell us to ignore it (for now).

**Comment by HendrikThePendric** [comment]
I also addressed a few unrelated minor UI issues in 548e757, 8c26ef0, 0266e77

**Review by radnov — APPROVED** [review]

**Comment by tonsV2** [comment]
@HendrikThePendric Great job! Thanks :pray:

**Pull request merged**
